services:
  - type: web
    name: community-care-connect
    runtime: static
    repo: https://github.com/Pat-rickJoyce/Community-Care-Connect
    branch: main
    buildCommand: ""
    staticPublishPath: .
